// Catálogo predefinido de equipamiento de gimnasio
export const EQUIPMENT_CATALOG = [
  // CARDIO
  { name: 'Cinta de Correr', category: 'CARDIO', maintenanceFrequencyDays: 30 },
  { name: 'Bicicleta Estática', category: 'CARDIO', maintenanceFrequencyDays: 30 },
  { name: 'Elíptica', category: 'CARDIO', maintenanceFrequencyDays: 30 },
  { name: 'Remo Ergómetro', category: 'CARDIO', maintenanceFrequencyDays: 45 },
  { name: 'Escaladora (StairMaster)', category: 'CARDIO', maintenanceFrequencyDays: 30 },
  { name: 'Bicicleta Spinning', category: 'CARDIO', maintenanceFrequencyDays: 30 },
  { name: 'Esquí de Fondo (Ski Erg)', category: 'CARDIO', maintenanceFrequencyDays: 45 },
  // STRENGTH
  { name: 'Press de Banca', category: 'STRENGTH', maintenanceFrequencyDays: 90 },
  { name: 'Sentadilla (Squat Rack)', category: 'STRENGTH', maintenanceFrequencyDays: 90 },
  { name: 'Press de Pierna (Leg Press)', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Extensión de Pierna', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Curl de Pierna', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Jalón al Pecho (Lat Pulldown)', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Remo en Polea', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Press de Hombros (Shoulder Press)', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Pec Deck (Mariposa)', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Curl de Bíceps en Máquina', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Extensión de Tríceps en Máquina', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Abductor / Aductor', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Hip Thrust Machine', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Multipower (Smith Machine)', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Cable Crossover', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  { name: 'Hack Squat', category: 'STRENGTH', maintenanceFrequencyDays: 60 },
  // FREE_WEIGHTS
  { name: 'Mancuernas (Set Completo)', category: 'FREE_WEIGHTS', maintenanceFrequencyDays: 180 },
  { name: 'Barra Olímpica', category: 'FREE_WEIGHTS', maintenanceFrequencyDays: 180 },
  { name: 'Discos de Peso', category: 'FREE_WEIGHTS', maintenanceFrequencyDays: 180 },
  { name: 'Kettlebells (Set)', category: 'FREE_WEIGHTS', maintenanceFrequencyDays: 180 },
  { name: 'Barra EZ', category: 'FREE_WEIGHTS', maintenanceFrequencyDays: 180 },
  { name: 'Banco Plano', category: 'FREE_WEIGHTS', maintenanceFrequencyDays: 90 },
  { name: 'Banco Inclinado', category: 'FREE_WEIGHTS', maintenanceFrequencyDays: 90 },
  { name: 'Banco Declinado', category: 'FREE_WEIGHTS', maintenanceFrequencyDays: 90 },
  // FUNCTIONAL
  { name: 'TRX / Suspensión', category: 'FUNCTIONAL', maintenanceFrequencyDays: 90 },
  { name: 'Battle Ropes', category: 'FUNCTIONAL', maintenanceFrequencyDays: 90 },
  { name: 'Caja Pliométrica', category: 'FUNCTIONAL', maintenanceFrequencyDays: 180 },
  { name: 'Balón Medicinal', category: 'FUNCTIONAL', maintenanceFrequencyDays: 180 },
  { name: 'Bosu Ball', category: 'FUNCTIONAL', maintenanceFrequencyDays: 180 },
  { name: 'Saco de Boxeo', category: 'FUNCTIONAL', maintenanceFrequencyDays: 90 },
  { name: 'Jaula Funcional (Rig)', category: 'FUNCTIONAL', maintenanceFrequencyDays: 90 },
  // ACCESSORIES
  { name: 'Colchonetas de Yoga/Pilates', category: 'ACCESSORIES', maintenanceFrequencyDays: 180 },
  { name: 'Bandas de Resistencia', category: 'ACCESSORIES', maintenanceFrequencyDays: 180 },
  { name: 'Foam Roller', category: 'ACCESSORIES', maintenanceFrequencyDays: 365 },
  { name: 'Cuerdas de Saltar', category: 'ACCESSORIES', maintenanceFrequencyDays: 180 },
  { name: 'Conos de Entrenamiento', category: 'ACCESSORIES', maintenanceFrequencyDays: 365 },
];
